// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpaceShopper.Infrastructure.Persistence.Catalog;

#nullable disable

namespace SpaceShopper.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpaceShopper.Domain.Entities.Catalog.Product", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PriceUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RatingAverage")
                        .HasColumnType("numeric");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("idClone")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("Product", "catalog");
                });

            modelBuilder.Entity("SpaceShopper.Domain.Entities.Catalog.Product", b =>
                {
                    b.OwnsOne("SpaceShopper.Domain.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("Productid")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("price_currency");

                            b1.HasKey("Productid");

                            b1.ToTable("Product", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("Productid");
                        });

                    b.OwnsOne("SpaceShopper.Domain.ValueObjects.Money", "RealPrice", b1 =>
                        {
                            b1.Property<Guid>("Productid")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("real_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("real_price_currency");

                            b1.HasKey("Productid");

                            b1.ToTable("Product", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("Productid");
                        });

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("RealPrice");
                });
#pragma warning restore 612, 618
        }
    }
}
